### ISSUE TITLE
Possible segmentation fault in Dsa crypto algorithm (keygen function)

### ISSUE THREAD

**Issue by TommasoBruni** [davxy/cry#10]
here the initialization's result is ignored and could cause a segmentation fault: https://github.com/crylib/cry/blob/dc35030b0b0081f8229a64ce7d8ec3b8c973436a/src/crypt/dsa.c#L155

**Comment by davxy** [comment]
<img src="https://c.tenor.com/mb0YYpwnapgAAAAM/high-way-road.gif" />

**Comment by davxy** [comment]
Fixed by #22dfbadbc2b638baf9197c53818a5e5dbcdca584
