### ISSUE TITLE
Ecdsa: unnecessary double release of two fields

### ISSUE THREAD

**Issue by TommasoBruni** [davxy/cry#11]
Here https://github.com/davxy/cry/blob/d30b18f185f9c7c9084b1e4f16ea754b30347db3/src/crypt/ecdsa.c#L90 the release of x and y fields is not necessary because it's already done here 
https://github.com/davxy/cry/blob/d30b18f185f9c7c9084b1e4f16ea754b30347db3/src/crypt/ecdsa.c#L89 (in the ecp_clear_list)

**Comment by davxy** [comment]
Fixed by #e1aea4a3fe41308d5a0c2ee530142cb06ee45993
